x = "Hello World"  # str
x = 20  # int
x = 20.5  # float
x = ["apple", "Banana", "Cherry"]  # list
x = ("apple", "Banana", "Cherry")  # tuple
x = {name: "pinyo", age: 21}  # dict
x = {"apple", "Banana", "Cherry"}  # set
x = frozenset({"apple", "Banana", "Cherry"})  # frozenset
x = True  # bool
x = b"hello"  # bytes
